# -*- coding: utf-8 -*-
"""Correlation_NBSS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXq1zFfREHbN6_myCgQw7y7xunetAq3b
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path = "/content/Pocra_district All Final Data_FINAL3MAY.xlsx"

sheets = pd.read_excel(file_path, sheet_name=None)

dfs = []
for sheet_name, df in sheets.items():
    if isinstance(df, pd.DataFrame) and not df.empty:
        df.columns = [col.strip().lower() for col in df.columns]
        if sheet_name.lower() == 'hingoli':
            cols = df.columns.tolist()
            if 'ud ld' in cols:
                idx = cols.index('ud ld')
                if idx + 1 < len(cols):
                    next_col = cols[idx + 1]
                    if next_col.strip() == '' or df[next_col].isna().all() or (df[next_col] == '').all():
                        df = df.rename(columns={'ud ld': 'ud', next_col: 'ld'})
        if 'lat' in df.columns:
            df['district'] = sheet_name
            dfs.append(df)


if dfs:
    df_merged = pd.concat(dfs, ignore_index=True)
    cols = df_merged.columns.tolist()
    lat_index = cols.index('lat')
    cols.insert(lat_index, cols.pop(cols.index('district')))
    df_merged = df_merged[cols]
    df_merged['lat'] = df_merged['lat'].ffill()
    df_merged['long'] = df_merged['long'].ffill()
    # print(df_merged)
else:
    print("No sheets with data and a 'lat' column were found.")

# df_merged.columns

def combine_columns(df, col_list, new_col):
    for col in col_list:
        if col in df.columns:
            if new_col in df.columns:
                df[new_col] = df[new_col].combine_first(df[col])
            else:
                df[new_col] = df[col]
    return df

col_variants = {
    'ud': ['ud', 'ud ld'],
    'ld': ['ld', 'unnamed: 4'],
    'site_id': ['site_id', 'unnamed: 3'],
    'bulk density': ['bulk density', 'bd'],
    'sand%': ['sand%', 'sand %'],
    'lab no.': ['lab no.', 'lab no', 'lab  no.'],
}

for main_col, variants in col_variants.items():
    df_merged = combine_columns(df_merged, variants, main_col)

to_drop = []
for main_col, variants in col_variants.items():
    for v in variants:
        if v != main_col and v in df_merged.columns:
            to_drop.append(v)
if to_drop:
    df_merged.drop(columns=to_drop, inplace=True)

cols = df_merged.columns.tolist()
main_cols = ['ud', 'ld', 'lab no.']
long_idx = cols.index('long') + 1
for c in reversed(main_cols):
    if c in cols:
        cols.insert(long_idx, cols.pop(cols.index(c)))
df_merged = df_merged[cols]
df_merged.drop(columns=['pwp.1', 'fc.1', 'awc.1'], inplace=True)
print(df_merged.columns)

df_merged.to_csv('nbss_all_villages_new.csv', index=False)
from google.colab import files
files.download('nbss_all_villages_new.csv')

latur = df_merged[:]
latur

latur.columns

latur['base saturation %'] = latur['base saturation %'].replace(r'^\s*$', np.nan, regex=True)

# latur['Base Saturation %'] = pd.to_numeric(latur['Base Saturation %'], errors='coerce')

latur.shape
latur["base saturation %"].mean()

mean_df = latur[['ph', 'ec mscm-1', 'organic carbon %', 'caco3 %', 'ex. ca+mg meq/100g soil',
       'ex.ca meq/100g soil', 'ex.mg meq/100g soil', 'ex.na meq/100g soil',
       'ex.k meq/100g soil', 'cec cmol(p+)kg-1', 'base saturation %',
       'av.n kg/ha', 'av.p kg/ha', 'av. k kg/ha', 'fe mg/kg', 'mn mg/kg',
       'cu mg/kg', 'zn mg/kg', 'sand%', '% clay', 'silt%',
       'bulk density', '1/3 bar %', '15 bar%', 'awc', 'wilting point',
       'field capacity', 'pwp', 'fc']].mean().to_frame().T
mean_df

"""# Correlation Analysis"""

df = pd.DataFrame(latur)
for_num_data = df[['ph', 'ec mscm-1', 'organic carbon %', 'caco3 %', 'ex. ca+mg meq/100g soil',
       'ex.ca meq/100g soil', 'ex.mg meq/100g soil', 'ex.na meq/100g soil',
       'ex.k meq/100g soil', 'cec cmol(p+)kg-1', 'base saturation %',
       'av.n kg/ha', 'av.p kg/ha', 'av. k kg/ha', 'fe mg/kg', 'mn mg/kg',
       'cu mg/kg', 'zn mg/kg', 'sand%', '% clay', 'silt%',
       'bulk density', '1/3 bar %', '15 bar%', 'awc', 'wilting point',
       'field capacity', 'pwp', 'fc']]
matrix = for_num_data.corr()

matrix

from matplotlib.colors import LinearSegmentedColormap
cmap = LinearSegmentedColormap.from_list(
    "red_white_green", ["darkred", "white", "darkgreen"]
)

plt.figure(figsize=(25, 18))
sns.heatmap(
    matrix.round(2),
    annot=True,
    fmt=".2f",
    cmap=cmap,
    vmin=-1, vmax=1,
    linewidths=0.5,
    cbar=True
)
plt.title("Correlation Heatmap")
plt.show()

cmap = LinearSegmentedColormap.from_list("red_white_green", ["darkred", "white", "darkgreen"])

plt.figure(figsize=(20, 18))

ax = sns.heatmap(
    matrix.round(2),
    # annot=True,
    fmt=".2f",
    cmap=cmap,
    vmin=-1, vmax=1,
    linewidths=0,
    cbar=True,
    xticklabels=True,   # Show x-axis (column) labels
    yticklabels=True    # Show y-axis (row) labels
)

ax.set_xticklabels(ax.get_xticklabels(), fontsize=16)
ax.set_yticklabels(ax.get_yticklabels(), fontsize=16)

plt.title("Correlation Heatmap", fontsize=20, fontweight='bold', pad=20)

# Put column labels at the top as well as bottom
ax.xaxis.set_ticks_position('top')
ax.xaxis.set_label_position('top')
plt.xticks(rotation=90, ha='left')

# Duplicate the x-axis tick labels at the bottom
ax_secondary = ax.secondary_xaxis('bottom')
ax_secondary.set_xticks(ax.get_xticks())
ax_secondary.set_xticklabels(ax.get_xticklabels(), fontsize=16)
ax_secondary.tick_params(axis='x', rotation=90)

# Duplicate the y-axis tick labels at the right
ax_secondary_y = ax.secondary_yaxis('right')
ax_secondary_y.set_yticks(ax.get_yticks())
ax_secondary_y.set_yticklabels(ax.get_yticklabels(), fontsize=16)
ax_secondary_y.tick_params(axis='y')

plt.tight_layout()
plt.show()

corr_pairs = (
    matrix.stack()
    .reset_index()
    .rename(columns={'level_0': 'Parameter 1', 'level_1': 'Parameter 2', 0: 'Correlation Value'})
)

corr_pairs = corr_pairs[corr_pairs['Parameter 1'] != corr_pairs['Parameter 2']]


corr_pairs['set'] = corr_pairs.apply(lambda x: frozenset([x['Parameter 1'], x['Parameter 2']]), axis=1)
corr_pairs = corr_pairs.drop_duplicates('set').drop(columns='set').reset_index(drop=True)

corr_pairs['Direction'] = np.where(corr_pairs['Correlation Value'] > 0, 'Positive', 'Negative')

def get_inference(x):
    abs_x = abs(x)
    if abs_x >= 0.7:
        return 'Very Strong'
    elif abs_x >= 0.5:
        return 'Strong'
    elif abs_x >= 0.25:
        return 'Good'
    elif abs_x >= 0.1:
        return 'Weak'
    else:
        return 'Very Weak'

corr_pairs['Inferance'] = corr_pairs['Correlation Value'].apply(get_inference)
corr_pairs['Correlation Value'] = corr_pairs['Correlation Value'].round(2)

final_corr_df = corr_pairs[['Parameter 1', 'Parameter 2', 'Correlation Value', 'Direction', 'Inferance']]

final_corr_df

def highlight_row(row):
    corr = row['Correlation Value']
    if corr >= 0.25:
        return ['background-color: #b6ffb6'] * len(row)  # light green
    elif corr <= -0.25:
        return ['background-color: #ffcccc'] * len(row)  # light red
    else:
        return [''] * len(row)

styled_df = final_corr_df.style.apply(highlight_row, axis=1)

styled_df

filtered_df = final_corr_df[
    (final_corr_df['Correlation Value'] >= 0.25) | (final_corr_df['Correlation Value'] <= -0.25)
].reset_index(drop=True)

filtered_df.style.apply(highlight_row, axis=1)

def get_corr_dict(df, direction):
    corr_dict = {}
    for _, row in df[df['Direction'] == direction].iterrows():
        corr_dict.setdefault(row['Parameter 1'], []).append(row['Parameter 2'])
        corr_dict.setdefault(row['Parameter 2'], []).append(row['Parameter 1'])

    for k in corr_dict:
        corr_dict[k] = list(sorted(set(corr_dict[k])))
    return corr_dict

pos_corr = get_corr_dict(filtered_df, 'Positive')
neg_corr = get_corr_dict(filtered_df, 'Negative')

all_params = sorted(set(list(pos_corr.keys()) + list(neg_corr.keys())))

summary_rows = []
for param in all_params:
    pos_with = ", ".join(pos_corr.get(param, []))
    neg_with = ", ".join(neg_corr.get(param, []))
    summary_rows.append({
        'Parameter': param,
        'Positive correlation with': pos_with,
        'Negative correlation with': neg_with
    })

summary_df = pd.DataFrame(summary_rows)
summary_df

summary_df.to_csv('overall_correlation.csv', index=False)
from google.colab import files
files.download('overall_correlation.csv')

"""marathawada, vidarbha
layer-wise
ydata profiling

# EDA Analysis
"""

print("Basic Overview:")
print("Shape:", latur.shape)
print("\nColumn Types:\n", latur.dtypes)
print("\nFirst 5 rows:\n", latur.head())
print("\nSummary (numerical):\n", latur.describe())
print("\nSummary (categorical):\n", latur.describe(include='object'))
print("\nMissing values:\n", latur.isnull().sum())



for col in latur.columns:
    print(f"\n--- {col} ---")
    print("Unique values:", latur[col].nunique())
    if latur[col].dtype == "object":
        print("Top 5 value counts:\n", latur[col].value_counts().head())
    else:
        print("Min:", latur[col].min(), "Max:", latur[col].max())

num_cols = for_num_data.select_dtypes(include=['number']).columns
axarr = for_num_data[num_cols].hist(bins=20, figsize=(20, 10))
plt.suptitle('Histograms for Numeric Columns')
plt.tight_layout(rect=[0, 0, 1, 0.96], h_pad=3.0, w_pad=2.0)  # increase h_pad for more vertical space

plt.show()

plt.figure(figsize=(20, 10))
for_num_data[num_cols].boxplot()
plt.title('Boxplots for Numeric Columns')
plt.xticks(rotation=45)
plt.show()

if len(num_cols) <= 10:
    sns.pairplot(for_num_data[num_cols])
    plt.suptitle('Pairplot for Numeric Columns', y=1.02)
    plt.show()

corr = for_num_data[num_cols].corr()
plt.figure(figsize=(20, 16))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", vmin=-1, vmax=1)
plt.title('Correlation Heatmap')
plt.show()

cat_cols = ["texture"]
col = "texture"
plt.figure(figsize=(8, 4))
latur[col].value_counts().head(5).plot(kind='bar')
plt.title(f"Top 5 value counts for {col}")
plt.ylabel("Count")
plt.xlabel(col)
plt.show()

plt.figure(figsize=(12, 6))
sns.heatmap(for_num_data.isnull(), cbar=False)
plt.title('Missing Values Heatmap')
plt.show()

print("\nColumns with most missing values:")
print(for_num_data.isnull().sum().sort_values(ascending=False).head(10))

print("\nHighly correlated variable pairs (>0.8):")
for col in corr.columns:
    for idx in corr.index:
        if col != idx and abs(corr.loc[idx, col]) > 0.8:
            print(f"{col} and {idx}: {corr.loc[idx, col]:.2f}")

num_cols = for_num_data.select_dtypes(include=['number']).columns

skewness = for_num_data[num_cols].skew()
kurtosis = for_num_data[num_cols].kurt()

summary_stats = pd.DataFrame({
    'Skewness': skewness,
    'Kurtosis': kurtosis
})
summary_stats



"""Vidarbha: Nagpur, Amravati, Akola, Gondiya, Bhandara, Yavtamal, Washim, Chandrapur, Gadhchiroli, Wardha and Buldhana...........
Marathwada: Aurangabad, Jalna, Beed, Parbhani, Latur, Nanded, Osmanabad and Hingoli
"""

# Vi: Amravati, Akola, Washmi, Wardha, Budhana
# Ma: Aurangabad, Jalna, Beed, Parbhani, Latur, Nanded, Osmanabad, Hindoli

for_num_data.head()

!pip install contextily

# --------------------------------------------
# 0.  Install the required packages once:
#     pip install pandas geopandas contextily folium shapely
# --------------------------------------------
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import contextily as cx
import matplotlib.pyplot as plt
import folium
from folium.plugins import MarkerCluster

# ------------------------------------------------------------
# 1.  Read or receive your dataframe (already in memory here)
#     Make sure lat/lon column names match yours exactly
# ------------------------------------------------------------
# df_merged = pd.read_csv("your_file.csv")   # example load
# ... or the dataframe is already defined …

LAT_COL  = "lat"
LON_COL  = "long"

# Keep only rows with finite coordinates
df_valid = df_merged[[LAT_COL, LON_COL]].dropna()
df_valid = df_valid[
    df_valid[LAT_COL].between(-90, 90) & df_valid[LON_COL].between(-180, 180)
]

# ------------------------------------------------------------
# 2A. STATIC MAP  (GeoPandas + Contextily)
# ------------------------------------------------------------
gdf = gpd.GeoDataFrame(
    df_valid,
    geometry=gpd.points_from_xy(df_valid[LON_COL], df_valid[LAT_COL]),
    crs="EPSG:4326",            # WGS-84
)
# Re-project to Web-Mercator for tiled basemaps
gdf_web = gdf.to_crs(epsg=3857)

fig, ax = plt.subplots(figsize=(10, 10))
gdf_web.plot(ax=ax, markersize=8, alpha=0.7, color="red", edgecolor="k", linewidth=0.2)
cx.add_basemap(ax, crs=gdf_web.crs, source=cx.providers.OpenStreetMap.Mapnik)
ax.set_axis_off()
plt.title("Locations from df_merged")
plt.tight_layout()
plt.savefig("locations_static_map.png", dpi=200)
plt.show()

print("Static map saved as locations_static_map.png")

# ------------------------------------------------------------
# 2B. INTERACTIVE MAP  (Folium)
#      – great for sharing; supports pan/zoom & pop-ups
# ------------------------------------------------------------
# Centre the map on the mean lat/lon
center_lat = df_valid[LAT_COL].mean()
center_lon = df_valid[LON_COL].mean()

m = folium.Map(location=[center_lat, center_lon], zoom_start=5, tiles="OpenStreetMap")

# Cluster markers if you have many points; switch to plain folium.Marker loop
# for datasets < ~500 points if you prefer.
cluster_layer = MarkerCluster().add_to(m)
for _idx, row in df_valid.iterrows():
    folium.Marker(
        location=[row[LAT_COL], row[LON_COL]],
        tooltip=f"({row[LAT_COL]:.4f}, {row[LON_COL]:.4f})"
    ).add_to(cluster_layer)

m.save("locations_interactive_map.html")
print("Interactive map saved as locations_interactive_map.html")

a,b = 0,0
dist = []
coordinates = []
for i in range(len(df_merged['long'])):
  if df_merged['long'][i] < 70 or df_merged['long'][i] > 80:
    a+= 1
    dist.append(df_merged['district'][i])
    coordinates.append(df_merged['long'][i])

for j in range(len(df_merged['lat'])):
  if df_merged['lat'][j] < 15 or df_merged['lat'][j] > 22:
    b+=1
    dist.append(df_merged['district'][j])
    coordinates.append(df_merged['lat'][j])

print("Count of distorted logitudes",a, "\nCount of distorted latitudes", b)
print(dist)
print(coordinates)

# Start with pH, AwC, soil type

"""Parbhani, Nanded, Hingoli, Aurangabad, Amravati, Budhana, Jalgaon, Washim, Nashik-Malegaon, Wardha, Akola, Beed, Jalna , Osmanabad"""
